### ISSUE TITLE
Upload Avatar Backend

### ISSUE THREAD

**Issue by Esseh** [mjrmyke/CSCI150Project#25]
There is an unfortunate fault at the moment in that the avatar upload isn't working. We will likely have to exclude the feature from this iteration. But that isn't my decision, that power goes to @mjrmyke .

Specifically, the handler meant to handle it will break. Two different defects occur depending on if a file is uploaded or not.
If one is uploaded it fails and serves an empty page(redirect fails.)
If one is not uploaded our server returns an error.

You can reproduce the bug by uncommenting the code in POST_ProfileEdit.

Because we do use avatars I propose continuing to use the placeholder so that our page aesthetics do not break.

**Comment by IIMasterXII** [comment]
I can give users a Pencil avatar with randomized attributes/colors according to their ID number. It was a feature I was planning on adding anyway.

**Comment by Esseh** [comment]
If you know how to do that, then that's great. Finish up the remainder of the project first though.

**Comment by IIMasterXII** [comment]
Will do. Creating note-cards for profile at the moment, and I also changed the CSS on new notes. I will replace the profile page avatar circle with the pencil svgs after that.

**Comment by mjrmyke** [comment]
Fixed the Avatar uploading, you may need to run gcloud auth. not too sure. If it doesnt work on your local machine, it will work when deployed. I am all for using the pencils instead of the avatars, or as the default user image instead of the font awesome user image. Currently, the avatar is not used at all on the site so we will need to do some integration for it either way. We will need something like this wherever the avatar is to be used, but customized to use the pencils if Erich can manage them.

`{{if .Avatar}}
<img src="{{getAvatarURL .IntID}}" alt="Avatar Image" class="user-avatar">
{{else}}
<svg class="user-avatar">
  <use xlink:href="#svg-user"></use>
</svg>
{{end}}`
